unpackaged/main/default/objects/Account/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Xero_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Xero_Contact_ID__c</fullName>
    <label>Xero Contact ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Xero_Log_Activity__c/Xero_Log_Activity__c.object-meta.xml
<CustomObject>
    <label>Xero Log Activity</label>
    <nameField>
        <displayFormat>XLA-{0000}</displayFormat>
        <label>Xero Log Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Log Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/UpdateXeroContactTest.cls
@isTest
public class UpdateXeroContactTest {
    @testSetup
    static void setup(){
        insert XeroTestDataFactory.createXeroSettings();
        insert XeroTestDataFactory.createXeroApiTokenRecord();

        Contact billingCont = XeroTestDataFactory.createContact();
        insert billingCont;

        Account acctRec = XeroTestDataFactory.createAccount();
        acctRec.Billing_Contact__c = billingCont.Id;
        insert acctRec;
    }

    @isTest
    static void testCallCreateAPI(){
        Test.setMock(HttpCalloutMock.class, new XeroApiHttpMock());

        List<Xero_Log_Activity__c> logActs = [SELECT Id FROM Xero_Log_Activity__c];
        Assert.areEqual(0, logActs.size());

        Account acctRec = [SELECT Id, Xero_Contact_ID__c FROM Account WHERE Name = 'Test Account'];
        Assert.isNull(acctRec.Xero_Contact_ID__c);

        Test.startTest();
        UpdateXeroContact.callCreateAPI(new List<Id>{acctRec.Id});
        Test.stopTest();

        acctRec = [SELECT Id, Xero_Contact_ID__c FROM Account WHERE Id = :acctRec.Id];
        Assert.areEqual('COOLID1234', acctRec.Xero_Contact_ID__c);

        logActs = [SELECT Id FROM Xero_Log_Activity__c];
        Assert.areEqual(1, logActs.size());
    }
}