unpackaged/main/default/objects/Account/fields/BillingAddressLine1__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressLine1__c</fullName>
    <description>Billing Address Line 1 - integrated with Zoey platform</description>
    <label>Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/BillingAddressLine2__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressLine2__c</fullName>
    <description>Billing address line 2 - integrated with Zoey platform</description>
    <label>Line 2/City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/BillingAddressLine3__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressLine3__c</fullName>
    <description>Billing Address Line 3 - integrated with Zoey platform</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/BillingAddressLine4__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressLine4__c</fullName>
    <description>Billing Address Line 4 - integrated with Zoey platform</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/BillingAddressPostcode__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressPostcode__c</fullName>
    <description>Billing Address Postcode - integrated with Zoey platform</description>
    <label>Postcode/ZIP/A2 CC</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <description>Account Email Address</description>
    <label>Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>Customer payment method</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Pay by Link</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TaxType__c.field-meta.xml
<CustomField>
    <fullName>TaxType__c</fullName>
    <description>Account tax type</description>
    <label>Tax Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Consumer</fullName>
            </value>
            <value>
                <fullName>Domestic Business</fullName>
            </value>
            <value>
                <fullName>International Consumer</fullName>
            </value>
            <value>
                <fullName>International Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

unpackaged/main/default/classes/CreateZoeyAccountTest.cls
@IsTest
public class CreateZoeyAccountTest {

    @IsTest
    static void scenario1() {
        
        Test.startTest();

        RequestMock fakeResponse = new RequestMock(200,'OK','{"total": 638,"page": 1,"pages": 128,"account_code": "1234"}',null);

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        Id standard = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();

        Account acct = new Account(
            Name                        = 'TestAcct',
            RecordTypeId                = standard,
            PaymentType__c              = 'Direct Debit', 
            BillingAddressLine1__c      = '1 The Street',
            BillingAddressLine2__c      = 'AddressLine2',
            BillingAddressLine3__c      = 'AddressLine3',
            BillingAddressLine4__c      = 'AddressLine4',
            BillingAddressPostcode__c   = 'SW12 3ED',
            EmailAddress__c             = 'test1234@gmail.com', 
            Phone                       = '+447800444444',
            TaxType__c                  = 'Domestic Business'
        );
        insert acct;  
        
        System.assert(acct.Id != null, 'Account record is created');

        List<Id> Ids = new  List<Id>();
        Ids.add(acct.Id);

        CreateZoeyAccount.callCreateAPI(Ids);

        Test.stopTest();

    }

    @IsTest
    static void scenario2() {
        
        Test.startTest();


        // RequestMock tokenFakeResponse = new RequestMock(200,'OK','{"token": "1234567"}', null);
        // Test.setMock(HttpCalloutMock.class, tokenFakeResponse);

        RequestMock fakeResponse = new RequestMock(200,'OK','{"token": "1234567","total": 638,"page": 1,"pages": 128,"account_code": "1234"}',null);

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        Id standard = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();

        Account acct = new Account(
            Name                        = 'TestAcct',
            RecordTypeId                = standard,
            PaymentType__c              = 'Direct Debit', 
            BillingAddressLine1__c      = '1 The Street',
            BillingAddressLine2__c      = 'AddressLine2',
            BillingAddressLine3__c      = 'AddressLine3',
            BillingAddressLine4__c      = 'AddressLine4',
            BillingAddressPostcode__c   = 'SW12 3ED',
            EmailAddress__c             = 'test1234@gmail.com', 
            Phone                       = '+447800444444',
            TaxType__c                  = 'Domestic Business'
        );
        insert acct;  
        
        System.assert(acct.Id != null, 'Account record is created');

        List<Id> Ids = new  List<Id>();
        Ids.add(acct.Id);

        CreateZoeyAccount.callCreateAPI(Ids);

        Test.stopTest();

    }

    @IsTest
    static void scenario3() {
        
        Test.startTest();


        // RequestMock tokenFakeResponse = new RequestMock(200,'OK','{"token": "1234567"}', null);
        // Test.setMock(HttpCalloutMock.class, tokenFakeResponse);

        RequestMock fakeResponse = new RequestMock(200,'OK','{"token": "1234567","total": 638,"page": 1,"pages": 128,"account_code": "1234"}',null);

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        Id standard = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();

        Account acct = new Account(
            Name                        = 'TestAcct',
            RecordTypeId                = standard,
            PaymentType__c              = 'Direct Debit', 
            BillingAddressLine1__c      = '1 The Street',
            BillingAddressLine2__c      = 'AddressLine2',
            BillingAddressLine3__c      = 'AddressLine3',
            BillingAddressLine4__c      = 'AddressLine4',
            BillingAddressPostcode__c   = 'SW12 3ED',
            EmailAddress__c             = 'test1234@gmail.com', 
            Phone                       = '+447800444444',
            TaxType__c                  = 'Domestic Consumer'
        );
        insert acct;  
        
        System.assert(acct.Id != null, 'Account record is created');

        List<Id> Ids = new  List<Id>();
        Ids.add(acct.Id);

        CreateZoeyAccount.callCreateAPI(Ids);

        Test.stopTest();

    }
}