unpackaged/main/default/objects/Account/fields/Xero_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Xero_Contact_ID__c</fullName>
    <label>Xero Contact ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Xero_API_Settings__c/Xero_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Xero API Settings</label>
</CustomObject>

unpackaged/main/default/objects/Xero_Invoice__c/Xero_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>XIN-{0000}</displayFormat>
        <label>Invoice Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Xero_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Amount_Credited__c.field-meta.xml
<CustomField>
    <fullName>Amount_Credited__c</fullName>
    <label>Amount Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Fully_Paid_On_Date__c.field-meta.xml
<CustomField>
    <fullName>Fully_Paid_On_Date__c</fullName>
    <label>Fully Paid On Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Invoice_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Due_Date__c</fullName>
    <label>Invoice Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Invoice_Reference__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Reference__c</fullName>
    <label>Invoice Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Authorised</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Paid__c.field-meta.xml
<CustomField>
    <fullName>Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/SubTotal__c.field-meta.xml
<CustomField>
    <fullName>SubTotal__c</fullName>
    <label>SubTotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/TotalTax__c.field-meta.xml
<CustomField>
    <fullName>TotalTax__c</fullName>
    <label>TotalTax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Xero_Invoice_ID__c.field-meta.xml
<CustomField>
    <fullName>Xero_Invoice_ID__c</fullName>
    <externalId>true</externalId>
    <label>Xero Invoice ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice_Line_Item__c/Xero_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>XLN-{0000}</displayFormat>
        <label>Xero Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Xero_Invoice_Line_Item__c/fields/Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Code__c</fullName>
    <label>Account Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice_Line_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <label>Item Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice_Line_Item__c/fields/Line_Amount__c.field-meta.xml
<CustomField>
    <fullName>Line_Amount__c</fullName>
    <label>Line Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice_Line_Item__c/fields/Unit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unit_Amount__c</fullName>
    <label>Unit Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice_Line_Item__c/fields/Xero_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Xero_Invoice__c</fullName>
    <label>Xero Invoice</label>
    <referenceTo>Xero_Invoice__c</referenceTo>
    <relationshipName>Xero_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice_Line_Item__c/fields/Xero_Line_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Xero_Line_Item_ID__c</fullName>
    <externalId>true</externalId>
    <label>Xero Line Item ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Xero_Log_Activity__c/Xero_Log_Activity__c.object-meta.xml
<CustomObject>
    <label>Xero Log Activity</label>
    <nameField>
        <displayFormat>XLA-{0000}</displayFormat>
        <label>Xero Log Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Log Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Xero_Log_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Xero Log Activities</relationshipLabel>
    <relationshipName>Xero_Log_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Xero_Log_Activity__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <label>Error Code</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Xero_Log_Activity__c/fields/JSON_Request__c.field-meta.xml
<CustomField>
    <fullName>JSON_Request__c</fullName>
    <label>JSON/Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Xero_Log_Activity__c/fields/Xero_ID__c.field-meta.xml
<CustomField>
    <fullName>Xero_ID__c</fullName>
    <label>Xero ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Xero_Log_Activity__c/fields/Xero_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Xero_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Xero Invoice</label>
    <referenceTo>Xero_Invoice__c</referenceTo>
    <relationshipLabel>Xero Log Activities</relationshipLabel>
    <relationshipName>Xero_Log_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ProcessXeroEventsBatch.cls
public class ProcessXeroEventsBatch implements Database.Batchable<String>, Database.AllowsCallouts, Database.Stateful{
    private final String webhookReqBody;
    private final List<String> xeroInvIds;

    public ProcessXeroEventsBatch(String webhookReqBody) {
        this.webhookReqBody = webhookReqBody;
        this.xeroInvIds = new List<String>();

        XeroWebhookRequest parsedWebhookReq = (XeroWebhookRequest)JSON.deserialize(webhookReqBody, XeroWebhookRequest.class);
        if(parsedWebhookReq != null && parsedWebhookReq.events != null && parsedWebhookReq.events.size() > 0){
            //Get Xero Contact/Invoice IDs
            for(XeroEvent xeroEvt : parsedWebhookReq.events){
                if(xeroEvt.eventCategory == 'INVOICE'){
                    if(!this.xeroInvIds.contains(xeroEvt.resourceId)){
                        this.xeroInvIds.add(xeroEvt.resourceId);
                    }
                }
            }
        }
    }

    public List<String> start(Database.BatchableContext bc){
        return this.xeroInvIds;
    }

    public void execute(Database.BatchableContext bc, List<String> scope){
        //Get Authentication settings
        Xero_API_Settings__c apiSettings = Xero_API_Settings__c.getOrgDefaults();

        List<Xero_Log_Activity__c> xeroLogActivities = new List<Xero_Log_Activity__c>();

        try{
            String tenantId = apiSettings.Tenant_ID__c;

            if(tenantId != null){
                //Variables to store new SF records
                List<Xero_Invoice__c> xeroInvoicesToUpsert = new List<Xero_invoice__c>();
                List<Xero_Invoice_Line_Item__c> xeroInvoiceLinesToUpsert = new List<Xero_Invoice_Line_Item__c>();

                //Create Xero Invoice and Xero Invoice Line Items
                List<XeroInvoiceAndLines> invAndLinesList = new List<XeroInvoiceAndLines>();
                if(!scope.isEmpty()){
                    HttpRequest req = XeroApiUtility.getXeroHttpRequest('GET', '/api.xro/2.0/Invoices', null);
                    req.setEndpoint(req.getEndpoint()+'?IDs='+String.join(scope, ','));
                    req.setHeader('xero-tenant-id', tenantId);
                    req.setTimeout(20000);
                    Http http = new Http();
                    HttpResponse resp = http.send(req);

                    System.debug('Xero GET Invoices Status: '+resp.getStatus()+' '+resp.getStatusCode());
                    System.debug('Xero GET Invoices Response Body: '+resp.getBody());
                    if(resp.getStatus() == 'OK' && resp.getStatusCode() == 200){
                        XeroInvoicesResponse xeroInvoicesResp = (XeroInvoicesResponse)JSON.deserialize(resp.getBody(), XeroInvoicesResponse.class);
                        System.debug('Xero GET Invoices Response Body Status: '+xeroInvoicesResp.Status);
                        if(xeroInvoicesResp.Status == 'OK'){
                            Map<String, Xero_Invoice__c> xeroInvoicesMap = new Map<String, Xero_Invoice__c>();
                            for(Xero_Invoice__c xeroInvoice : [SELECT 
                                                                    Id, 
                                                                    Xero_Invoice_ID__c,
                                                                    (SELECT
                                                                            Id,
                                                                            Xero_Line_Item_ID__c
                                                                        FROM
                                                                            Xero_Invoice_Line_Items__r) 
                                                                FROM Xero_Invoice__c 
                                                                WHERE Xero_Invoice_ID__c IN :scope]){
                                xeroInvoicesMap.put(xeroInvoice.Xero_Invoice_ID__c, xeroInvoice);
                            }
                            
                            Set<String> xeroContactIds = new Set<String>();
                            for(XeroInvoice xeroInv : xeroInvoicesResp.Invoices){
                                if(xeroInv.Type == 'ACCREC' && xeroInv.Status != 'DRAFT' && xeroInv.Status != 'SUBMITTED'){
                                    xeroContactIds.add(xeroInv.Contact.ContactId);
                                }
                            }
                            
                            Map<String, Account> accountsMap = new Map<String, Account>();
                            for(Account acctRec : [SELECT Id, Xero_Contact_ID__c FROM Account WHERE Xero_Contact_ID__c IN :xeroContactIds]){
                                accountsMap.put(acctRec.Xero_Contact_ID__c, acctRec);
                            }

                            for(XeroInvoice xeroInv : xeroInvoicesResp.Invoices){
                                if(xeroInv.Type == 'ACCREC' && xeroInv.Status != 'DRAFT' && xeroInv.Status != 'SUBMITTED'){
                                    if(accountsMap.containsKey(xeroInv.Contact.ContactID)){
                                        XeroInvoiceAndLines invAndLines = new XeroInvoiceAndLines();
                                        invAndLines.xeroInvoice = xeroInv;
                                        invAndLines.xeroLineItems = xeroInv.LineItems;
        
                                        Xero_Invoice__c updatedXeroInv = new Xero_Invoice__c(
                                            Id = (xeroInvoicesMap.containsKey(xeroInv.InvoiceID) ? xeroInvoicesMap.get(xeroInv.InvoiceID).Id : null),
                                            Account__c = accountsMap.get(xeroInv.Contact.ContactId).Id,
                                            Amount_Credited__c = xeroInv.AmountCredited,
                                            Amount_Due__c = xeroInv.AmountDue,
                                            Amount_Paid__c = xeroInv.AmountPaid,
                                            Fully_Paid_On_Date__c = (xeroInv.FullyPaidOnDate != null ? getConvertedEpoch(xeroInv.FullyPaidOnDate) : null),
                                            Invoice_Date__c = (xeroInv.DateString != null ? Date.valueOf(xeroInv.DateString) : null),
                                            Invoice_Due_Date__c = (xeroInv.DueDateString != null ? Date.valueOf(xeroInv.DueDateString) : null),
                                            Invoice_Reference__c = xeroInv.Reference,
                                            Invoice_Number__c = xeroInv.InvoiceNumber,
                                            Invoice_Status__c = xeroInv.Status,
                                            Paid__c = (xeroInv.Status != null && xeroInv.Status == 'PAID' ? true : false),
                                            SubTotal__c = xeroInv.SubTotal,
                                            Total__c = xeroInv.Total,
                                            TotalTax__c = xeroInv.TotalTax,
                                            Xero_Invoice_ID__c = xeroInv.InvoiceID 
                                        );
                                        xeroInvoicesToUpsert.add(updatedXeroInv);
                                        invAndLines.sfXeroInvoice = updatedXeroInv;
        
                                        if(xeroInv.LineItems != null && xeroInv.LineItems.size() > 0){
                                            //Get existing Xero Invoice Line Items and put to Map if any
                                            List<Xero_Invoice_Line_Item__c> existingLineItems = (xeroInvoicesMap.containsKey(xeroInv.InvoiceID) ? xeroInvoicesMap.get(xeroInv.InvoiceID).Xero_Invoice_Line_Items__r : new List<Xero_Invoice_Line_Item__c>());
                                            Map<String, Xero_Invoice_Line_Item__c> lineItemIdToLineItemMap = new Map<String, Xero_Invoice_Line_Item__c>();
                                            for(Xero_Invoice_Line_Item__c xeroLineItem : existingLineItems){
                                                lineItemIdToLineItemMap.put(xeroLineItem.Xero_Line_Item_ID__c, xeroLineItem);
                                            }
                                            
                                            invAndLines.sfXeroLineItems = new List<Xero_Invoice_Line_Item__c>();
                                            for(XeroLineItem xeroLineItem : xeroInv.LineItems){
                                                Xero_Invoice_Line_Item__c updatedXeroLineItm = new Xero_Invoice_Line_Item__c(
                                                    Id = (lineItemIdToLineItemMap.containsKey(xeroLineItem.LineItemID) ? lineItemIdToLineItemMap.get(xeroLineItem.LineItemID).Id : null),
                                                    Account_Code__c = xeroLineItem.AccountCode,
                                                    Description__c = xeroLineItem.Description,
                                                    Item_Code__c = xeroLineItem.ItemCode,
                                                    Line_Amount__c = xeroLineItem.LineAmount,
                                                    Quantity__c = xeroLineItem.Quantity,
                                                    Unit_Amount__c = xeroLineItem.UnitAmount,
                                                    Xero_Line_Item_ID__c = xeroLineItem.LineItemID
                                                );
                                                xeroInvoiceLinesToUpsert.add(updatedXeroLineItm);
                                                invAndLines.sfXeroLineItems.add(updatedXeroLineItm);
                                            }
                                        }
        
                                        //Xero Log Activity creation
                                        invAndLines.logActivity = new Xero_Log_Activity__c(
                                            Object__c = 'Xero Invoice',
                                            Action__c = (updatedXeroInv.Id == null ? 'Create in Salesforce' : 'Update in Salesforce'),
                                            Xero_ID__c = invAndLines.xeroInvoice.InvoiceID,
                                            JSON_Request__c = webhookReqBody
                                        );  

                                        invAndLinesList.add(invAndLines);

                                    }
                                }
                            }
                        }
                    }
                }

                //Upsert Xero Invoice and Xero Lines
                if(invAndLinesList.size() > 0){
                    //Upsert Xero Invoices
                    upsert xeroInvoicesToUpsert;

                    if(xeroInvoiceLinesToUpsert.size() > 0){
                        for(XeroInvoiceAndLines invAndLines : invAndLinesList){
                            for(Xero_Invoice_Line_Item__c xeroLineItem : invAndLines.sfXeroLineItems){
                                if(xeroLineItem.Id == null){
                                    xeroLineItem.Xero_Invoice__c = invAndLines.sfXeroInvoice.Id;
                                }
                            }
                        }

                        //Upsert Xero Invoice Lines
                        upsert xeroInvoiceLinesToUpsert;
                    }

                    for(XeroInvoiceAndLines invAndLines : invAndLinesList){
                        invAndLines.logActivity.Xero_Invoice__c = invAndLines.sfXeroInvoice.Id;
                        invAndLines.logActivity.Outcome__c = 'Success';

                        xeroLogActivities.add(invAndLines.logActivity);
                    }
                }
            } else {
                throw new XeroApiException('No Xero Tenant ID found.');
            }
        } catch(Exception ex){
            System.debug('stack trace: '+ex.getStackTraceString());
            System.debug('error: '+ex.getMessage());
            xeroLogActivities.add(new Xero_Log_Activity__c(
                Object__c = 'Xero Invoice',
                Action__c = 'Create in Salesforce',
                Outcome__c = 'Error',
                Error_Code__c = ex.getMessage(),
                JSON_Request__c = webhookReqBody
            ));
        }
    }

    public void finish(Database.BatchableContext bc){

    }

    public Date getConvertedEpoch(String str){
        String epochTime = str.substringBetween('(',')').subStringBefore('+');
        Long timestamp = Long.valueOf(epochTime);
        return Date.valueOf(DateTime.newInstance(timestamp));
    }

    public class XeroWebhookRequest {
        public List<XeroEvent> events;
    }

    public class XeroEvent {
        public String resourceUrl;
        public String resourceId;
        public String tenantId;
        public String tenantType;
        public String eventCategory;
        public String eventType;
        public String eventDateUtc;
    }

    public class XeroContactsResponse {
        public String Id;
        public String Status;
        public String ProviderName;
        public String DateTimeUTC;
        public List<XeroContact> Contacts;
    }

    public class XeroContact {
        public String ContactID;
        public String Name;
    }

    public class XeroInvoicesResponse {
        public String Id;
        public String Status;
        public String ProviderName;
        public String DateTimeUTC;
        public List<XeroInvoice> Invoices;
    }

    public class XeroInvoice {
        public Decimal AmountCredited;
        public Decimal AmountDue;
        public Decimal AmountPaid;
        public String FullyPaidOnDate;
        public String DateString;
        public String DueDateString;
        public String Reference;
        public String InvoiceNumber;
        public String Status;
        public Decimal SubTotal;
        public Decimal Total;
        public Decimal TotalTax;
        public String Type;
        public XeroContact Contact;
        public String InvoiceID;
        public List<XeroLineItem> LineItems;
    }

    public class XeroLineItem {
        public String AccountCode;
        public String Description;
        public String ItemCode;
        public Decimal LineAmount;
        public Decimal Quantity;
        public Decimal UnitAmount;
        public String LineItemID;
    }

    public class XeroInvoiceAndLines {
        public XeroInvoice xeroInvoice;
        public Xero_Invoice__c sfXeroInvoice;
        public List<XeroLineItem> xeroLineItems;
        public List<Xero_Invoice_Line_Item__c> sfXeroLineItems;
        public Xero_Log_Activity__c logActivity;
    }
}