unpackaged/main/default/objects/Account/fields/Xero_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Xero_Contact_ID__c</fullName>
    <label>Xero Contact ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Xero_API_Settings__c/Xero_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Xero API Settings</label>
</CustomObject>

unpackaged/main/default/objects/Xero_API_Settings__c/fields/Webhook_Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Webhook_Private_Key__c</fullName>
    <label>Webhook Private Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Xero_Invoice__c/Xero_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>XIN-{0000}</displayFormat>
        <label>Invoice Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Xero_Invoice_Line_Item__c/Xero_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>XLN-{0000}</displayFormat>
        <label>Xero Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Xero_Invoice_Line_Item__c/fields/Xero_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Xero_Invoice__c</fullName>
    <label>Xero Invoice</label>
    <referenceTo>Xero_Invoice__c</referenceTo>
    <relationshipName>Xero_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/XeroWebhookHandlerTest.cls
@isTest
public class XeroWebhookHandlerTest {
    @testSetup
    static void setup(){
        insert XeroTestDataFactory.createXeroSettings();
        insert XeroTestDataFactory.createXeroApiTokenRecord();

        Account acctRec = XeroTestDataFactory.createAccount();
        acctRec.Xero_Contact_ID__c = 'COOLID1234';
        insert acctRec;
    }

    @isTest
    static void testWebhookHandler(){
        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/XeroWebhookHandler/';
        req.httpMethod = 'POST';

        //Create test webhook request
        ProcessXeroEventsBatch.XeroWebhookRequest webhookReq = new ProcessXeroEventsBatch.XeroWebhookRequest();
        webhookReq.events = new List<ProcessXeroEventsBatch.XeroEvent>();
        ProcessXeroEventsBatch.XeroEvent xeroEvt = new ProcessXeroEventsBatch.XeroEvent();
        xeroEvt.resourceId = 'SOMEINVID12345';
        xeroEvt.eventCategory = 'INVOICE';
        webhookReq.events.add(xeroEvt);

        req.requestBody = Blob.valueOf(JSON.serialize(webhookReq));

        Xero_API_Settings__c settings = Xero_API_Settings__c.getOrgDefaults();

        req.headers.put('x-xero-signature', XeroWebhookHandler.generateHmacSHA256Signature(req.requestBody.toString(), settings.Webhook_Private_Key__c));
        RestContext.request = req;

        RestResponse res = new RestResponse();
        RestContext.response = res;

        List<Xero_Invoice__c> invoices = [SELECT Id FROM Xero_Invoice__c];
        Assert.areEqual(0, invoices.size());

        List<Xero_Invoice_Line_Item__c> invoiceLines = [SELECT Id FROM Xero_Invoice_Line_Item__c];
        Assert.areEqual(0, invoiceLines.size());

        Test.setMock(HttpCalloutMock.class, new XeroApiHttpMock());

        Test.startTest();
        XeroWebhookHandler.handleWebhookRequest();
        Test.stopTest();

        invoices = [SELECT Id FROM Xero_Invoice__c];
        Assert.areEqual(1, invoices.size());

        invoiceLines = [SELECT Id FROM Xero_Invoice_Line_Item__c];
        Assert.areEqual(2, invoiceLines.size());
    }
}