unpackaged/main/default/objects/Xero_API_Settings__c/Xero_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Xero API Settings</label>
</CustomObject>

unpackaged/main/default/objects/Xero_API_Settings__c/fields/Xero_API_Tokens_Record_Name__c.field-meta.xml
<CustomField>
    <fullName>Xero_API_Tokens_Record_Name__c</fullName>
    <label>Xero API Tokens Record Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Xero_API_Tokens__c/Xero_API_Tokens__c.object-meta.xml
<CustomObject>
    <label>Xero API Tokens</label>
    <nameField>
        <label>Xero API Tokens Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xero API Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Xero_API_Tokens__c/fields/Expires_In__c.field-meta.xml
<CustomField>
    <fullName>Expires_In__c</fullName>
    <label>Expires In</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/XeroTokenRefreshBatchTest.cls
@isTest
public class XeroTokenRefreshBatchTest {
    @testSetup
    static void setup(){
        insert XeroTestDataFactory.createXeroSettings();
        insert XeroTestDataFactory.createXeroApiTokenRecord();
    }

    @isTest
    static void testExecuteBatch(){
        Test.setMock(HttpCalloutMock.class, new XeroApiHttpMock());

        Test.startTest();
        Database.executeBatch(new XeroTokenRefreshBatch());
        Test.stopTest();
        
        Xero_API_Settings__c settings = Xero_API_Settings__c.getOrgDefaults();

        List<Xero_API_Tokens__c> apiTokens = [SELECT Id, Access_Token__c, Refresh_Token__c, Expires_In__c FROM Xero_API_Tokens__c WHERE Name = :settings.Xero_API_Tokens_Record_Name__c];
        Assert.areEqual('REFTOKEN123REFRESH', apiTokens[0].Refresh_Token__c);
        Assert.areEqual('ACCTOKEN123REFRESH', apiTokens[0].Access_Token__c);
        Assert.isNotNull(apiTokens[0].Expires_In__c);
    }
}