unpackaged/main/default/objects/Xero_API_Settings__c/Xero_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Xero API Settings</label>
</CustomObject>

unpackaged/main/default/objects/Xero_API_Settings__c/fields/Xero_API_Tokens_Record_Name__c.field-meta.xml
<CustomField>
    <fullName>Xero_API_Tokens_Record_Name__c</fullName>
    <label>Xero API Tokens Record Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Xero_API_Tokens__c/Xero_API_Tokens__c.object-meta.xml
<CustomObject>
    <label>Xero API Tokens</label>
    <nameField>
        <label>Xero API Tokens Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xero API Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Xero_API_Tokens__c/fields/Expires_In__c.field-meta.xml
<CustomField>
    <fullName>Expires_In__c</fullName>
    <label>Expires In</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/XeroTokenRefreshBatch.cls
public class XeroTokenRefreshBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful, Database.AllowsCallouts {
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new XeroTokenRefreshBatch(), 1);
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        Xero_API_Settings__c settings = Xero_API_Settings__c.getOrgDefaults();
        String xeroApiTokensRecName = settings.Xero_API_Tokens_Record_Name__c;
        String query = 'SELECT Id, Access_Token__c, Refresh_Token__c, Expires_In__c FROM Xero_API_Tokens__c WHERE Name = :xeroApiTokensRecName';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Xero_API_Tokens__c> scope) {
        Xero_API_Tokens__c xeroApiTokens = scope[0];
        XeroAuthUtility.refreshAccessToken(xeroApiTokens);
    }

    public void finish(Database.BatchableContext BC){

    }
}