unpackaged/main/default/objects/Xero_Invoice__c/Xero_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>XIN-{0000}</displayFormat>
        <label>Invoice Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Xero_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/InvoiceBatchTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-15-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class InvoiceBatchTest {
    @TestSetup
    static void makeData(){

        Account acc = new Account(
            Name = 'Test Account'
        );
        insert acc;

        List<Xero_Invoice__c> invoices = new  List<Xero_Invoice__c>();
        
        for( Integer i = 1; i < 10; i++ ){
            Xero_Invoice__c invoice = new Xero_Invoice__c(
                Account__c = acc.Id
            );
            
            invoices.add(invoice);
        }

        insert invoices;

    }

    @isTest
    static void scenario() {

        List<Xero_Invoice__c> invoices = [SELECT Id FROM Xero_Invoice__c];
        System.debug('Xero_Invoice' + invoices);

        Test.startTest();
        System.schedule('Invoice Update', '0 6 * * * ?', new InvoiceScheduler());
        Test.stopTest();
    }
}