unpackaged/main/default/objects/Xero_Invoice__c/Xero_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>XIN-{0000}</displayFormat>
        <label>Invoice Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Xero_Invoice__c/fields/Invoice_Batch_Last_Update__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Batch_Last_Update__c</fullName>
    <label>Invoice Batch Last Update</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/InvoiceBatch.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-15-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global with sharing class InvoiceBatch implements Database.Batchable<sObject> {
    global Database.Querylocator start(Database.BatchableContext bc){
        String query = 'SELECT Id FROM Xero_Invoice__c';
        return Database.getQuerylocator(query);
    } 

    global void execute(Database.BatchableContext bc, List<Xero_Invoice__c> invoices){
        System.debug('Execute' + invoices.size());

        if( invoices.size() > 0 ){
            for( Xero_Invoice__c invoice : invoices ){
                invoice.Invoice_Batch_Last_Update__c = DateTime.now();
            }
        }

        System.debug('invoices invoices invoices' + invoices);
        update invoices;
    }

    global void finish(Database.BatchableContext bc){
        System.debug('Finish');
    }
}